// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkdpwdaddcymcvclcczc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZHB3ZGFkZGN5bWN2Y2xjY3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTQ1MzcsImV4cCI6MjA2MDAzMDUzN30.0wcx59ehCpZe9VNNuinJVGpyuQ2MBm5qf0PnhykSX9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);